# Generated by eigenform's release workflow — edits here are overwritten each release.
class Eigenform < Formula
  desc "Control surface over Claude Code sessions"
  homepage "https://github.com/rdmontgomery/eigenform"
  version "0.1.314"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/rdmontgomery/eigenform/releases/download/v0.1.314/eigenform-aarch64-apple-darwin.tar.gz"
      sha256 "b30433ca0a29ffa1736ac90301525ea5133c624ae6b8d000f43d01ff607523c0"
    end
    on_intel do
      url "https://github.com/rdmontgomery/eigenform/releases/download/v0.1.314/eigenform-x86_64-apple-darwin.tar.gz"
      sha256 "2ae8192c1c01aec8767e8c82c58ed9e43fce99e755f46d71461535ec6c43d72b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rdmontgomery/eigenform/releases/download/v0.1.314/eigenform-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "e10d9831fed5b66e6922031af5f126ebb074220be671a5228b7886ff4e89ebcc"
    end
  end

  def install
    bin.install "eigenform"
    bin.install_symlink "eigenform" => "ef"
  end

  def caveats
    <<~EOS
      An already-running daemon keeps serving the old version after an upgrade.
      `ef` prints a note when that happens; `ef stop && ef` switches over
      (this ends open sessions).
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/eigenform --version")
  end
end
