# Generated by eigenform's release workflow — edits here are overwritten each release.
class Eigenform < Formula
  desc "Control surface over Claude Code sessions"
  homepage "https://github.com/rdmontgomery/eigenform"
  version "0.1.308"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/rdmontgomery/eigenform/releases/download/v0.1.308/eigenform-aarch64-apple-darwin.tar.gz"
      sha256 "64b345dd9f0e5c977af236de42462cd378a1c3e2d51a2dc5979c226681308fa8"
    end
    on_intel do
      url "https://github.com/rdmontgomery/eigenform/releases/download/v0.1.308/eigenform-x86_64-apple-darwin.tar.gz"
      sha256 "82d04a8aa53b9aa2bffc2842842cfbd211de7155e26232719757a61d100a1026"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rdmontgomery/eigenform/releases/download/v0.1.308/eigenform-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "db8e4f0f5a271a3b3b8bd09f9d6714e53de887510a2991e65baa23e0b624ba2d"
    end
  end

  def install
    bin.install "eigenform"
    bin.install_symlink "eigenform" => "ef"
  end

  def caveats
    <<~EOS
      An already-running daemon keeps serving the old version after an upgrade.
      `ef` prints a note when that happens; `ef stop && ef` switches over
      (this ends open sessions).
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/eigenform --version")
  end
end
