# Generated by eigenform's release workflow — edits here are overwritten each release.
class Eigenform < Formula
  desc "Control surface over Claude Code sessions"
  homepage "https://github.com/rdmontgomery/eigenform"
  version "0.1.312"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/rdmontgomery/eigenform/releases/download/v0.1.312/eigenform-aarch64-apple-darwin.tar.gz"
      sha256 "20ca24b2d13a2abe20f503583d3256e52add5808c0d88fd9334c17530e94ffb3"
    end
    on_intel do
      url "https://github.com/rdmontgomery/eigenform/releases/download/v0.1.312/eigenform-x86_64-apple-darwin.tar.gz"
      sha256 "e90a3de18945a2d45a6e12ce1d5a24a860e14169000101e4fc36befaff1e23c1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rdmontgomery/eigenform/releases/download/v0.1.312/eigenform-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "e3e3720cf5e6754bc1e7d578faea44adaf2d4abf3afd489e0c266c18f87d7940"
    end
  end

  def install
    bin.install "eigenform"
    bin.install_symlink "eigenform" => "ef"
  end

  def caveats
    <<~EOS
      An already-running daemon keeps serving the old version after an upgrade.
      `ef` prints a note when that happens; `ef stop && ef` switches over
      (this ends open sessions).
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/eigenform --version")
  end
end
